apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgACDFuZrbJq5k1SfVK7DXBGXwIDwwVyH5ECi69qmPGkSUHWJccuNv7OBBSy8UjhdNYqmZzcCo+VOoRE2zss/215hhdBgt59WSmBWYPTvWnxTjd4GMjWspAm8OIh7PQTwfXB9Kas9FkCYMD6eTpmSStuhi9bSpPGCFTcI6KnQUm2j4nzU0hpiwyTOAxJp+R6a0WGdBNFokDfznpqg7vItrWcYkF5y/y2nHxWhxKfktStBpCBoSMtpCXt+y+SDNsrcr6e4vQQyHtt+p3iGwICI3XQ62fhVzU+zY4OhFpvn7ajHjZ2/kluIEt2ebeBN+2z2BCCrKxqMv1Uec4Y9epW66W19NjSwlhxx75vVfOPMPakMZC7XgKTf+CV2/PxYwVEeQRWiADB9DJVyoDse2s+jmk9Ck9iie3rjtw1muAafavYa+w0opdKKgu/LKOJTsdVnSJlPkLcJMiv1vrfW3poWqJ8JkdEYKTLqzg3eN7MJpz8UpqnKuA1nvhwJmoT1pDWjh/GcIZifyytHrA9N59tJb/xcM5neoWt5wKMJviH4s+s4VB23ABLPPG9CGBXh+bXjGvb78zBKBvhMi/a4tBtZiuOQk6apUx1ClSC3CWzfmXxEE03xFw9InvBQmZ1ybZgF7+2AnbtFpWrkTfsgyURyQk4SxugKVR++THQmxHRh+P3Rf868NYGjw/c2lZuuIhJHE2XTDmv9oh8IPusAghHqzN0QFQGlVtqhw+uWAP65EjN95YJXmR99d9UHK7WPzJcwp4rjg8LR/pt/8OI0yLQ9RGRI5kuQKNJPlbNSIaLKLMYAhuMMrSFHb858o9zr8fm3dMbi3v2h2/uqDUHcaEFI7GiDCV7AS+eEilfUZVtD1/xWxqp95TWyb/jv/LTBcJAoeIVjvBeX1ib5kDSyEJqrV7nKQF2686rk6H6rTNPL7dhRsXLGFqyLTyQJkLkpyORXREm8krIEBSmqO7ufnUThb3DrJAtrxWRr8IV9IZYr36ZuBuNKv3hpupXdv981ITvy9lgo2RaiGm2DyuERHUSqjaP5wzRurXFYouCOSVw6nSTbdNyDWoDVOjvc+CP9eTOxfZFzRiDo1l4NBX636gyEGds5ISR2Lk4+tqdptDvYWO7lmqtVLpRIjqddyI2jJdTbfBrXzPhy+mY/UFjuJBdjn7VkXfgWZZprkpppOjUAwC5GXuFkm8Bhp+C/8e3W5wGEf2dOVUwhwnI3Y7Gxw9pmB9NW6gt5eY8tFoeHGWI6prGVnlJuufYQyK0mG+DWfD5jdmNlO3TVsufLW9yKYytUs2MpD88XN/VgAwm1a6U8VuJ5adC/rLl+E+P4P1d3EN370I/pV15WAlMybLtmusvLEaqMWTpvE2oo72qrDWftQzBa4YMW5Ps
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

